### ISSUE TITLE
What is the best practice for JS interaction?

### ISSUE THREAD

**Issue by AskAlice** [joedf/Webapp.ahk#1]
for GUI, it's a necessity it seems. I have some checkboxes that work with materialize, and unless I add some sleeps before and after I run the update function (which updates from certain hotkeys being pressed), otherwise the checkboxes won't update. Now, I would debug js with a console, but it seems there isn't one... lol. I'm not sure if this is just an issue with materialize. Not sure any other way to update 

    sendJS(js) {
    wb := getDOM()
    wb.Navigate("javascript:" . js)
    }

And, my update code, and yes, please laugh because it looks disgusting as I tried many ways to make if faster, sometimes it wouldn't update at all. I did try to interact with the DOM directly with wb but that didn't seem to make much of a difference, and it didn't trigger the animations that make the radio boxes appear active/inactive

```
updateToggles(afk,tram,gard){
	wb := getDOM()
	sleep, 50
		if(!afk && !tram &&  !gard)
	{
			sleep, 150
		sendJS("clearStatus();")
		
		OutputDebug Cleared
}else{
	if(afk && wb.Document.getElementById("afk-switch").checked != afk)
	{
			sendJS("updateStatus('a', true)")
		OutputDebug Updated AFK
	}else if(tram && wb.Document.getElementById("trampoline-switch").checked != tram)
	{
			sendJS("updateStatus('t', true)")
			OutputDebug Updated Trampoline
	}else
	if(gard && wb.Document.getElementById("garden-switch").checked !=gard)
	{
		sendJS("updateStatus('g', true)")
	}
}
sleep, 250
}
```

```
<ul class="tabs tabs-transparent tabs-fixed-width" style="height:auto;">
			<li class="tab"><a href="#main" class="active">Main Page</a></li>
			<li class="tab" id="atab"><a href="#afk">Anti-AFK</a><input class="with-gap" name="toggles" type="radio" id="afk-switch" /><label for="afk-switch">CTRL+SHIFT+1</label></li>
			<li class="tab" id="ttab"><a href="#trampoline">Trampoline Bot</a><input class="with-gap" name="toggles" type="radio" id="trampoline-switch" /><label for="trampoline-switch">CTRL+SHIFT+2</label></li>
			<li class="tab" id="gtab"><a href="#garden">Gardening Bot</a><input class="with-gap" name="toggles" type="radio" id="garden-switch" /><label for="garden-switch">CTRL+SHIFT+4</label></li>
			<li class="tab"><a href="#fishing">Fishing Hack Guide</a></li>
    </ul>
```

```
function updateStatus(control,status){
			if(control == "t"){
				$('#ttab input').prop("checked", true)
			}else if(control == "a"){
				$('#atab input').prop("checked", true)
			}else if(control == "g"){
				$('#gtab input').prop("checked", true)
			}else{
				console.log("$('" + control + "').prop('checked'," + status + ")");
			$(control).prop("checked",status);
			}
		}
		function clearStatus(){
			$('.tabs input:radio').removeAttr('checked')
		}
```

**Comment by AskAlice** [comment]
This was somewhat fixed by removing the css transitions from the switch. I set the delay to 50, when it's zero it doesn't update after clearing, but it works much faster. Who needs fancy transitions anyway.

**Comment by joedf** [comment]
Wow! I'm so sorry. I didn't see this till now!
Hmmm, I see... Yes this must be something weird with IE...

**Comment by AskAlice** [comment]
:-) No problem. It's working for the most part, just a bit buggy only when it comes to that. Thanks for making this
