### ISSUE TITLE
Why dont return value from global variable, ON LOAD PAGE?

### ISSUE THREAD

**Issue by luisely** [joedf/Webapp.ahk#2]
When I use a gloval variable from AHK for load with the page, does not work

Have any Idea?

Example? 

```AutoHotkey
global test := "Simple Test"`

app_page(NewURL) {
	wb := getDOM()
	if InStr(NewURL,"index.html") {
		Sleep, 10
		x := wb.document.getElementById("ahk_info")
		x.innerHTML := GetAHK_EnvInfo()
	}
}
GetAHK_EnvInfo(){
	return "IP: " . A_IPAddress1 . %test%
}
```

HTML

```HTML
<p><small id="ahk_info"><small></p>
```

![image](https://user-images.githubusercontent.com/20712618/28729361-9d7c0b4a-73a2-11e7-9c21-eeaacf463629.png)

**Comment by joedf** [comment]
Since `return` expects an expression, do not enclose `test` in `%` signs. That's for indirect variable-referencing (AHK is looking for the value of the vaiable name "Simple Test" which is nothing/undefined).
```AutoHotkey
GetAHK_EnvInfo(){
	return "IP: " . A_IPAddress1 . test
}
```

**Comment by luisely** [comment]
OK, this works! simple... thk you

But I don't understand why this happening ...

I Read a file TXT, but dont show on load page.

```ahk 

global aviso := ""

UrlDownloadToFile, http://192.168.1.56/arquivos/avisos/aviso.txt, c:\microsiga_p11\aviso.txt
FileRead, aviso, c:\microsiga_p11\aviso.txt

app_page(NewURL) {
	wb := getDOM()
	if InStr(NewURL,"index.html") {
		Sleep, 10
		x := wb.document.getElementById("ahk_info")
		x.innerHTML := GetAHK_EnvInfo2()
	}
}

GetAHK_EnvInfo2(){
	return aviso
}
```

```HTML
<textarea readonly id="ahk_info" rows="10" cols="100"></textarea> 
```

does not work on load page... textarea still blank

**Comment by joedf** [comment]
That's because when the page is first being created the function `app_page` is being called before the main thread of the application is run. This is a little quirky, yes. 

I suggest to do something like this instead:
```ahk 
app_page(NewURL) {
	wb := getDOM()
	if InStr(NewURL,"index.html") {
		Sleep, 10
		x := wb.document.getElementById("ahk_info")
		x.innerHTML := GetAHK_EnvInfo2()
	}
}

GetAHK_EnvInfo2(){
	global aviso
	dFile := "http://192.168.1.56/arquivos/avisos/aviso.txt"
	sFile := "c:\microsiga_p11\aviso.txt"
	if !FileExist(sFile)
		UrlDownloadToFile, %dFile%, %sFile%
	FileRead, aviso, %sFile%
	return aviso
}
```

**Comment by luisely** [comment]
Oohh! perfect.!!

thank you!!

**Comment by joedf** [comment]
No problem :+1:
