### ISSUE TITLE
simple question  - Start in Full Screen

### ISSUE THREAD

**Issue by luisely** [joedf/Webapp.ahk#3]
A dumb question... in Json file I can set the resolution for GUI,  ok.

But I want the app starts on full Screen, how I can do that? @joedf

**Comment by joedf** [comment]
Fullscreen is not a supported feature. Easy to implement, I'll try to add this tonight.

**Comment by luisely** [comment]
Oh, Will be awesome! @joedf .

Thanks!

**Comment by joedf** [comment]
Here we go
https://github.com/joedf/Webapp.ahk/commit/3bad43d16ca37f688275fc74d2519323e4545938

usage explained here
https://github.com/joedf/Webapp.ahk/blob/master/README.md
