### ISSUE TITLE
Which version of IE is used?

### ISSUE THREAD

**Issue by usernamehw** [joedf/Webapp.ahk#5]
I want to know which features (`HTML` / `CSS` / `JavaScript`) are available. For that I need to know the version of IE.

Tried searching, but didn't find anything.

**Comment by joedf** [comment]
It is set to use the latest version of IE that is installed. You can launch IE on your system and check the version in there. IE11 is included in all Windows 10 distributions. 
You should be able to use all ES5 features without issue. You might have to set the following meta tag to avoid certain problems: `<meta http-equiv='X-UA-Compatible' content='IE=edge'>`

**Comment by usernamehw** [comment]
Thanks for the quick response. Does that mean it will always target `IE 11` and not `Edge 18`?

**Comment by usernamehw** [comment]
It looks like Edge doesn't support ActiveX.

**Comment by joedf** [comment]
No worries. 👍 
Only IE11, Edge is not considered IE.

**Comment by Sharps** [comment]
Spent all day trying to figure out why jQuery and Socket.io would be spitting out errors and it was that one meta tag that for some reason I decided I didn't need in the beginning. Gotta pay more attention...

**Comment by joedf** [comment]
Thanks for sharing and glad it works now! 👍
