### ISSUE TITLE
JS page load function not being run when changing pages

### ISSUE THREAD

**Issue by woodsy1** [joedf/Webapp.ahk#6]
Hey there,
I have been playing around with this and love it!
I have encountered an issue where the jquery (or JS for that matter) page on load functions only run when the application is loaded and not each time you change between pages.

Similarly the "app_page" function runs each time but doesnt run JS functions after the initial page load.

example:
```
$(function() {
		BuildDropDowns();
	});
```
This runs when page is loaded first time but when I click a link to another page and then come back the function no longer runs

Thoughts?

**Comment by woodsy1** [comment]
to further prove this point... In your default project on first load you get this:
![image](https://user-images.githubusercontent.com/13148552/70672665-07ef7700-1cd4-11ea-8cf3-6719e2e1e52b.png)

However if you click to page 1 and then back to index you get this:
![image](https://user-images.githubusercontent.com/13148552/70672684-1a69b080-1cd4-11ea-9521-c2874d716f63.png)

I have narrowed this a little bit by confirming that AHK function does run each load but it seems like the DOM load functions arent run each time... 
It also seems like AHK can talk to the DOM on first load but the JS functions calls arent run on the second load so perhaps there are actually 2 issues?

**Comment by woodsy1** [comment]
I also found this: https://www.autohotkey.com/boards/viewtopic.php?t=38416 
Looks as if he was having the same issue as me (although he didnt correctly identify the problem) and came up with a pretty hacky way around it! 

EDIT - which still didnt actually solve the issue of the on load events in JS not working!

**Comment by joedf** [comment]
No, you're completely right! Thanks for reporting this. I put the link like that in the example because I was having the same issue. I think I've fixed it! 😃 

Could you try the new version out for me?

**Comment by woodsy1** [comment]
I think that solves 1 of the issues (AHK can now talk to the DOM in that load function as proven by your function running each load) 
however for me I think this is the issue:
```
$(function() {
		BuildDropDowns();

	});
```

This function DOES run on first page load but NOT on the second load

**Comment by joedf** [comment]
You mean like page refresh?

**Comment by woodsy1** [comment]
Hmm its hard to explain what I mean I guess! 
So on first load of the application the html page runs the JS as outlined above and calls the BuildDropDowns function.
when I navigate away and then back to the page the onLoad function as defined above no longer runs.

I have also noticed that if I call the function directly from the "app_page" function using:
```
window := getWindow()
window.BuildDropDowns()
```
This also doesnt work HOWEVER if I put a MsgBox in it DOES call the function correctly?!
```
MsgBox Hello from JS_AHK :)
	
window := getWindow()
window.BuildDropDowns()
```

**Comment by woodsy1** [comment]
Another SUPER strange inconsistency with this is if I "double click" the link that redirects me to the page the first of the above works as it should.....

In fact this seems to be quite consistent! a Single click doesnt seem to run the JS functions but a double click does?!

**Comment by joedf** [comment]
Hmm... Not sure...
It could be how the links are being handled. There's also cheap trick being used to reattach `JS_AHK()` on Lbutton click (`gosub,__Webapp_JS_AHK_Attach`), but I'm not sure if it's the culprit here...

Do have any code (maybe a reduced version of what you have) I could use to test this out?

**Comment by woodsy1** [comment]
Not quite sure how to cut it down to get the parts you need to look at but here is the git hub
https://github.com/woodsy1/Webapp.ahk/tree/master/src

Basically what needs looking at is the index.html and the example.ahk files.
This function on line 99: `function BuildDropDowns()`
The link on line 38 (which is what I am clicking)

and then the `app_page` function on line 489 of the example file

**Comment by woodsy1** [comment]
Its almost like there is some sort of race condition. 
If I put `MsgBox Hello from JS_AHK :)` on line 502 it throws the popup and once I dismiss that the function gets called correctly and works fine?! 🤷‍♂

**Comment by woodsy1** [comment]
Interestingly it looks like DOM minipulation works fine (what yours is doing) but function calling is NOT.

```
;not working on the second load UNLESS double clicked
window := getWindow()
window.BuildDropDowns()
        
;Workings as we are expecting it should
wb := getDOM()
x := wb.document.getElementById("log")
x.innerHTML := "<i>Webapp.ahk is currently running on " . GetAHK_EnvInfo() . ".</i>"
```

**Comment by joedf** [comment]
Okok, I tested it with your files. Thanks, by the way! I think I've fixed it. 😄 
The internal `js->ahk` function  wasn't being attached on page load, only on clicks.
It should work now. Try revision 4 and let me know! 👍 

Also, don't forget to star the repo if you like this project 😁

**Comment by woodsy1** [comment]
Woohoo man that has solved the onload issue and it now runs every page load! 

Great work and thanks for quick turn around time on it!

**Comment by joedf** [comment]
Awesome! 😄 👍

**Comment by woodsy1** [comment]
its good cause I had just thought of a crazy hack work around that I didnt want to have to use!
I was going to use the DOM editing method and then have an OnChange event on that to run my function! haha

**Comment by joedf** [comment]
Interesting! 💭
